module_label('character')
module_menu('   convert','modules/character/convert.js')
module_menu('   in out','modules/character/in%20out.js')
module_menu('   parse','modules/character/parse.js')
module_menu('   variable','modules/character/variable.js')
module_label('connect')
module_label('   stl')
module_menu('      stl','modules/connect/stl/stl.js')
module_label('   svg')
module_menu('      ExtractFaces','modules/connect/svg/ExtractFaces.js')
module_menu('      Honeycomb','modules/connect/svg/Honeycomb.js')
module_menu('      PCB','modules/connect/svg/PCB.js')
module_menu('      SelectFace','modules/connect/svg/SelectFace.js')
module_label('convert')
module_label('   rgba')
module_menu('      jpg','modules/convert/rgba/jpg.js')
module_menu('      png','modules/convert/rgba/png.js')
module_label('   svg')
module_menu('      array','modules/convert/svg/array.js')
module_menu('      image','modules/convert/svg/image.js')
module_label('defaults')
module_menu('   Carbide Nomad defaults','modules/defaults/Carbide%20Nomad%20defaults.js')
module_menu('   defaults','modules/defaults/defaults.js')
module_menu('   Othermill defaults','modules/defaults/Othermill%20defaults.js')
module_menu('   PCB defaults (mm)','modules/defaults/PCB%20defaults%20(mm).js')
module_menu('   PCB defaults','modules/defaults/PCB%20defaults.js')
module_menu('   Roland Mill defaults','modules/defaults/Roland%20Mill%20defaults.js')
module_menu('   vbit calculator','modules/defaults/vbit%20calculator.js')
module_label('dev')
module_menu('   hellod3','modules/dev/hellod3.js')
module_menu('   log','modules/dev/log.js')
module_menu('   send raw','modules/dev/send%20raw.js')
module_label('event')
module_menu('   delay','modules/event/delay.js')
module_menu('   generate','modules/event/generate.js')
module_menu('   pause','modules/event/pause.js')
module_menu('   sequence','modules/event/sequence.js')
module_label('file')
module_menu('   append','modules/file/append.js')
module_menu('   save','modules/file/save.js')
module_label('frep')
module_label('   operators')
module_menu('      add','modules/frep/operators/add.js')
module_menu('      blend','modules/frep/operators/blend.js')
module_menu('      clearance','modules/frep/operators/clearance.js')
module_menu('      intersect','modules/frep/operators/intersect.js')
module_menu('      morph','modules/frep/operators/morph.js')
module_menu('      subtract','modules/frep/operators/subtract.js')
module_label('   shapes 2D')
module_menu('      arc','modules/frep/shapes%202D/arc.js')
module_menu('      circle','modules/frep/shapes%202D/circle.js')
module_menu('      function','modules/frep/shapes%202D/function.js')
module_menu('      involute gear','modules/frep/shapes%202D/involute%20gear.js')
module_menu('      involute rack','modules/frep/shapes%202D/involute%20rack.js')
module_menu('      polygon','modules/frep/shapes%202D/polygon.js')
module_menu('      rectangle','modules/frep/shapes%202D/rectangle.js')
module_menu('      right triangle','modules/frep/shapes%202D/right%20triangle.js')
module_menu('      triangle','modules/frep/shapes%202D/triangle.js')
module_label('   shapes 3D')
module_menu('      cone','modules/frep/shapes%203D/cone.js')
module_menu('      cube','modules/frep/shapes%203D/cube.js')
module_menu('      cylinder','modules/frep/shapes%203D/cylinder.js')
module_menu('      function','modules/frep/shapes%203D/function.js')
module_menu('      lattice','modules/frep/shapes%203D/lattice.js')
module_menu('      menger','modules/frep/shapes%203D/menger.js')
module_menu('      pyramid','modules/frep/shapes%203D/pyramid.js')
module_menu('      sphere','modules/frep/shapes%203D/sphere.js')
module_menu('      torus','modules/frep/shapes%203D/torus.js')
module_label('   transforms')
module_menu('      extrude','modules/frep/transforms/extrude.js')
module_menu('      inflate','modules/frep/transforms/inflate.js')
module_menu('      reflect','modules/frep/transforms/reflect.js')
module_menu('      repeat linear','modules/frep/transforms/repeat%20linear.js')
module_menu('      repeat rotary','modules/frep/transforms/repeat%20rotary.js')
module_menu('      revolve','modules/frep/transforms/revolve.js')
module_menu('      rotate','modules/frep/transforms/rotate.js')
module_menu('      scale','modules/frep/transforms/scale.js')
module_menu('      shear','modules/frep/transforms/shear.js')
module_menu('      shell','modules/frep/transforms/shell.js')
module_menu('      slice','modules/frep/transforms/slice.js')
module_menu('      taper','modules/frep/transforms/taper.js')
module_menu('      translate','modules/frep/transforms/translate.js')
module_label('   view')
module_menu('      render (CPU)','modules/frep/view/render%20(CPU).js')
module_menu('      render (GPU)','modules/frep/view/render%20(GPU).js')
module_menu('      slice','modules/frep/view/slice.js')
module_label('image')
module_menu('   boundingbox','modules/image/boundingbox.js')
module_menu('   color separation','modules/image/color%20separation.js')
module_menu('   crop','modules/image/crop.js')
module_menu('   distance transform','modules/image/distance%20transform.js')
module_menu('   dogbone','modules/image/dogbone.js')
module_menu('   edge detect','modules/image/edge%20detect.js')
module_menu('   function','modules/image/function.js')
module_menu('   invert','modules/image/invert.js')
module_menu('   motion detect','modules/image/motion%20detect.js')
module_menu('   offset','modules/image/offset.js')
module_menu('   orient edges','modules/image/orient%20edges.js')
module_menu('   palette','modules/image/palette.js')
module_menu('   raster mask','modules/image/raster%20mask.js')
module_menu('   size','modules/image/size.js')
module_menu('   sum','modules/image/sum.js')
module_menu('   tabs','modules/image/tabs.js')
module_menu('   threshold','modules/image/threshold.js')
module_menu('   vector mask','modules/image/vector%20mask.js')
module_menu('   vectorize','modules/image/vectorize.js')
module_label('input')
module_menu('   video','modules/input/video.js')
module_label('iterate')
module_menu('   step and delay','modules/iterate/step%20and%20delay.js')
module_menu('   step','modules/iterate/step.js')
module_label('library')
module_menu('   globals','modules/library/globals.js')
module_menu('   library','modules/library/library.js')
module_menu('   threejs','modules/library/threejs.js')
module_label('math')
module_menu('   benchmark','modules/math/benchmark.js')
module_menu('   dyadic','modules/math/dyadic.js')
module_menu('   glsl_benchmark','modules/math/glsl_benchmark.js')
module_menu('   parallel','modules/math/parallel.js')
module_menu('   scalar','modules/math/scalar.js')
module_label('mesh')
module_menu('   height map','modules/mesh/height%20map.js')
module_menu('   rotate','modules/mesh/rotate.js')
module_menu('   slice raster','modules/mesh/slice%20raster.js')
module_label('module')
module_menu('   blank','modules/module/blank.js')
module_menu('   create','modules/module/create.js')
module_menu('   delete','modules/module/delete.js')
module_menu('   move','modules/module/move.js')
module_label('network')
module_menu('   apa','modules/network/apa.js')
module_label('object')
module_menu('   construct','modules/object/construct.js')
module_menu('   download','modules/object/download.js')
module_menu('   set','modules/object/set.js')
module_menu('   string','modules/object/string.js')
module_menu('   view','modules/object/view.js')
module_label('path')
module_label('   formats')
module_menu('      dxf','modules/path/formats/dxf.js')
module_menu('      g-code Carbide Nomad','modules/path/formats/g-code%20Carbide%20Nomad.js')
module_menu('      g-code','modules/path/formats/g-code.js')
module_menu('      gerber','modules/path/formats/gerber.js')
module_menu('      hpgl','modules/path/formats/hpgl.js')
module_menu('      multi_g-code','modules/path/formats/multi_g-code.js')
module_menu('      svg','modules/path/formats/svg.js')
module_label('   machines')
module_label('      EDM')
module_menu('         Viteris','modules/path/machines/EDM/Viteris.js')
module_label('      large mill')
module_menu('         ShopBot','modules/path/machines/large%20mill/ShopBot.js')
module_label('      laser cutter')
module_menu('         Epilog','modules/path/machines/laser%20cutter/Epilog.js')
module_menu('         Trotec','modules/path/machines/laser%20cutter/Trotec.js')
module_label('      precision mill')
module_menu('         Roland MDX-iModela','modules/path/machines/precision%20mill/Roland%20MDX-iModela.js')
module_menu('         Roland SRM20 CBA','modules/path/machines/precision%20mill/Roland%20SRM20%20CBA.js')
module_menu('         Roland SRM20 NC','modules/path/machines/precision%20mill/Roland%20SRM20%20NC.js')
module_menu('         Roland SRM20 RML','modules/path/machines/precision%20mill/Roland%20SRM20%20RML.js')
module_menu('         TinyG','modules/path/machines/precision%20mill/TinyG.js')
module_label('      vinyl cutter')
module_menu('         GCC','modules/path/machines/vinyl%20cutter/GCC.js')
module_menu('         Roland GX-GS-24','modules/path/machines/vinyl%20cutter/Roland%20GX-GS-24.js')
module_menu('         Silhouette Cameo','modules/path/machines/vinyl%20cutter/Silhouette%20Cameo.js')
module_label('   view')
module_menu('      panelize toolpath','modules/path/view/panelize%20toolpath.js')
module_menu('      view multi_toolpath','modules/path/view/view%20multi_toolpath.js')
module_menu('      view toolpath','modules/path/view/view%20toolpath.js')
module_label('processes')
module_label('   cut')
module_menu('      raster','modules/processes/cut/raster.js')
module_label('   mill raster')
module_menu('      2.5D','modules/processes/mill%20raster/2.5D.js')
module_menu('      2D','modules/processes/mill%20raster/2D.js')
module_menu('      2D_dual','modules/processes/mill%20raster/2D_dual.js')
module_menu('      2D_triple','modules/processes/mill%20raster/2D_triple.js')
module_menu('      3D','modules/processes/mill%20raster/3D.js')
module_label('   scan')
module_menu('      line','modules/processes/scan/line.js')
module_label('read')
module_menu('   hpgl','modules/read/hpgl.js')
module_menu('   png','modules/read/png.js')
module_menu('   stl','modules/read/stl.js')
module_menu('   svg','modules/read/svg.js')
module_menu('   text','modules/read/text.js')
module_label('socket')
module_menu('   device','modules/socket/device.js')
module_menu('   echo','modules/socket/echo.js')
module_menu('   print','modules/socket/print.js')
module_menu('   pyserial','modules/socket/pyserial.js')
module_menu('   serial','modules/socket/serial.js')
module_menu('   udp','modules/socket/udp.js')
module_menu('   websocket','modules/socket/websocket.js')
module_label('string')
module_menu('   format','modules/string/format.js')
module_menu('   variables','modules/string/variables.js')
module_label('ui')
module_menu('   bar graph','modules/ui/bar%20graph.js')
module_menu('   button window','modules/ui/button%20window.js')
module_menu('   color','modules/ui/color.js')
module_menu('   label simple','modules/ui/label%20simple.js')
module_menu('   label','modules/ui/label.js')
module_menu('   note','modules/ui/note.js')
module_menu('   slider','modules/ui/slider.js')
module_menu('   switch','modules/ui/switch.js')
module_menu('   text window','modules/ui/text%20window.js')
module_label('webserial')
module_menu('   potentiometer thing','modules/webserial/potentiometer%20thing.js')
module_menu('   rgb thing','modules/webserial/rgb%20thing.js')
module_menu('   servo_thing','modules/webserial/servo_thing.js')
module_menu('   Urumbu','modules/webserial/Urumbu.js')
module_menu('   urumbu_movement','modules/webserial/urumbu_movement.js')
module_menu('   webhid','modules/webserial/webhid.js')
module_menu('   webserial','modules/webserial/webserial.js')
module_menu('   webusb','modules/webserial/webusb.js')

