program_label('formats')
program_menu('   gerber plot','programs/formats/gerber%20plot')
program_label('frep')
program_menu('   gears','programs/frep/gears')
program_menu('   lattice torus','programs/frep/lattice%20torus')
program_menu('   smiley','programs/frep/smiley')
program_label('image')
program_menu('   function','programs/image/function')
program_menu('   motion detect','programs/image/motion%20detect')
program_menu('   palette mask raster','programs/image/palette%20mask%20raster')
program_menu('   palette mask vector','programs/image/palette%20mask%20vector')
program_menu('   vectorize','programs/image/vectorize')
program_label('iterate')
program_menu('   z theta scan','programs/iterate/z%20theta%20scan')
program_label('machines')
program_label('   Carbide Nomad')
program_menu('      PCB','programs/machines/Carbide%20Nomad/PCB')
program_label('   Carvera')
program_menu('      mill 2D PCB','programs/machines/Carvera/mill%202D%20PCB')
program_menu('      mill 2D PCB all','programs/machines/Carvera/mill%202D%20PCB%20all')
program_label('   Epilog')
program_menu('      cut','programs/machines/Epilog/cut')
program_label('   G-code')
program_menu('      mill 2.5D stl','programs/machines/G-code/mill%202.5D%20stl')
program_menu('      mill 2D','programs/machines/G-code/mill%202D')
program_menu('      mill 2D PCB','programs/machines/G-code/mill%202D%20PCB')
program_menu('      mill 3D stl','programs/machines/G-code/mill%203D%20stl')
program_label('   GCC')
program_menu('      gcc vinyl cut','programs/machines/GCC/gcc%20vinyl%20cut')
program_label('   Generic laser cutter')
program_menu('      cut','programs/machines/Generic%20laser%20cutter/cut')
program_label('   Othermill-Bantam Tools')
program_menu('      PCB','programs/machines/Othermill-Bantam%20Tools/PCB')
program_menu('      wax','programs/machines/Othermill-Bantam%20Tools/wax')
program_label('   Oxford')
program_menu('      engrave 2D','programs/machines/Oxford/engrave%202D')
program_label('   Roland')
program_label('      GX-GS 24 vinyl cutters')
program_menu('         cut','programs/machines/Roland/GX-GS%2024%20vinyl%20cutters/cut')
program_label('      iModela mill')
program_menu('         PCB','programs/machines/Roland/iModela%20mill/PCB')
program_label('      MDX mill')
program_menu('         PCB','programs/machines/Roland/MDX%20mill/PCB')
program_label('      SRM-20 mill')
program_menu('         mill 2.5D stl','programs/machines/Roland/SRM-20%20mill/mill%202.5D%20stl')
program_menu('         mill 2D','programs/machines/Roland/SRM-20%20mill/mill%202D')
program_menu('         mill 2D PCB','programs/machines/Roland/SRM-20%20mill/mill%202D%20PCB')
program_menu('         mill 3D stl','programs/machines/Roland/SRM-20%20mill/mill%203D%20stl')
program_label('   ShopBot')
program_menu('      mill 2.5D stl','programs/machines/ShopBot/mill%202.5D%20stl')
program_menu('      mill 2D','programs/machines/ShopBot/mill%202D')
program_menu('      mill 2D PCB','programs/machines/ShopBot/mill%202D%20PCB')
program_menu('      mill 3D stl','programs/machines/ShopBot/mill%203D%20stl')
program_label('   Silhouette')
program_menu('      cut','programs/machines/Silhouette/cut')
program_label('   Trotec')
program_menu('      cut','programs/machines/Trotec/cut')
program_label('   Viteris')
program_menu('      cut','programs/machines/Viteris/cut')
program_label('math')
program_menu('   benchmark','programs/math/benchmark')
program_menu('   expressions','programs/math/expressions')
program_label('processes')
program_label('   cut')
program_label('      raster')
program_menu('         video','programs/processes/cut/raster/video')
program_label('   mill')
program_label('      raster')
program_menu('         2.5D','programs/processes/mill/raster/2.5D')
program_menu('         2D','programs/processes/mill/raster/2D')
program_menu('         PCB to SVG','programs/processes/mill/raster/PCB%20to%20SVG')
program_label('variable')
program_menu('   text variables','programs/variable/text%20variables')
program_label('websocket')
program_menu('   blink','programs/websocket/blink')
program_label('xdesign connect')
program_menu('   Epilog cut','programs/xdesign%20connect/Epilog%20cut')
program_menu('   G-code mill 2.5D stl','programs/xdesign%20connect/G-code%20mill%202.5D%20stl')
program_menu('   RNDMC honeycomb','programs/xdesign%20connect/RNDMC%20honeycomb')
program_menu('   Roland GS24 cut','programs/xdesign%20connect/Roland%20GS24%20cut')
program_menu('   Roland SRM20 mill 2.5D stl','programs/xdesign%20connect/Roland%20SRM20%20mill%202.5D%20stl')
program_menu('   Roland SRM20 PCB','programs/xdesign%20connect/Roland%20SRM20%20PCB')
program_menu('   Shopbot mill 2.5D stl','programs/xdesign%20connect/Shopbot%20mill%202.5D%20stl')
program_menu('   Shopbot mill 2D svg','programs/xdesign%20connect/Shopbot%20mill%202D%20svg')

